# Generated by Django 3.2 on 2023-01-27 15:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_id', models.PositiveIntegerField(blank=True, null=True)),
                ('car_model_id', models.PositiveIntegerField(blank=True, null=True)),
                ('part_id', models.PositiveIntegerField(blank=True, null=True)),
                ('model_year', models.PositiveIntegerField(blank=True, null=True)),
                ('on_add', models.BooleanField()),
                ('on_sale', models.BooleanField()),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
