# Generated by Django 3.2 on 2023-01-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='model_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='part_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
