# Generated by Django 3.2 on 2023-01-27 15:06

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('friendly_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_category', models.CharField(max_length=50)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.make')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=254, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('grade', models.CharField(choices=[('A (Perfect)', 'A'), ('B (Great)', 'B'), ('C (Good)', 'C'), ('D (Fair)', 'D')], max_length=12)),
                ('fuel', models.CharField(blank=True, choices=[('Petrol', 'PETROL'), ('Diesel', 'DIESEL'), ('Electric', 'ELECTRIC'), ('Hybrid', 'HYBRID')], default=None, max_length=8, null=True)),
                ('side', models.CharField(blank=True, choices=[('Driver side', 'DS'), ('Passenger side', 'PS'), ('Driver side rear', 'DSR'), ('Driver side front', 'DSF'), ('Passenger side rear', 'PSR'), ('Passenger side front', 'PSF')], default=None, max_length=21, null=True)),
                ('on_sale', models.BooleanField(default=False)),
                ('sale_percentage', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('image', models.ImageField(blank=True, max_length=1024, null=True, upload_to='')),
                ('in_a_cart', models.BooleanField(default=False)),
                ('is_sold', models.BooleanField(default=False)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.model')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.color')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.make')),
                ('model_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.year')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.part')),
            ],
        ),
    ]
