# Generated by Django 3.2 on 2023-01-01 19:03

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.DateField()),
                ('vehicle_category', models.CharField(max_length=50)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.make')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=254, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('grade', models.CharField(choices=[('A', 'A (Perfect)'), ('B', 'B (Great)'), ('C', 'C (Good)'), ('D', 'D (Fair)')], max_length=1)),
                ('color', models.CharField(blank=True, choices=[('WHITE', 'White'), ('BLACK', 'Black'), ('GRAY', 'Gray'), ('SILVER', 'Silver'), ('BLUE', 'Blue'), ('RED', 'red'), ('BROWN', 'Brown'), ('GREEN', 'Green'), ('ORANGE', 'Orange'), ('BEIGE', 'Beige'), ('PURPLE', 'Purple'), ('GOLD', 'Gold'), ('YELLOW', 'Yellow'), ('INDIGO', 'Indigo'), ('VIOLET', 'Violet')], default=None, max_length=6, null=True)),
                ('fuel', models.CharField(blank=True, choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid')], default=None, max_length=8, null=True)),
                ('side', models.CharField(blank=True, choices=[('DS', 'Driver side'), ('PS', 'Passenger side'), ('DSR', 'Driver side rear'), ('DSF', 'Driver side front'), ('PSR', 'Passenger side rear'), ('PSF', 'Passenger side front')], default=None, max_length=3, null=True)),
                ('on_sale', models.BooleanField(default=False)),
                ('sale_percentage', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.model')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.part')),
            ],
        ),
    ]
