# Generated by Django 3.2 on 2023-01-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vehicle_category',
            field=models.CharField(blank=True, choices=[('Sedan', 'SEDAN'), ('Hatchback', 'HATCHBACK'), ('SUV', 'SUV'), ('Coupe', 'COUPE'), ('Pickup', 'PICKUP'), ('Van/Minivan', 'VAN/MINIVAN'), ('Convertible', 'CONVERTIBLE'), ('Motorbike', 'MOTORBIKE')], max_length=21, null=True),
        ),
    ]
