# Generated by Django 3.2 on 2023-01-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_friendly_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='year',
        ),
        migrations.AddField(
            model_name='model',
            name='model_year',
            field=models.IntegerField(default=1000),
        ),
    ]
