# Generated by Django 3.2 on 2023-01-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20230104_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=1024, null=True, upload_to=''),
        ),
    ]
