# Generated by Django 3.2 on 2023-02-03 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_model_make'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='make',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.make'),
        ),
        migrations.AlterField(
            model_name='product',
            name='car_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.model'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='make',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.make'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.year'),
        ),
        migrations.AlterField(
            model_name='product',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.part'),
        ),
    ]
